source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'therubyracer'
gem 'mysql2', '~> 0.3.20'

# UI/UX
gem 'bootstrap-sass'
gem 'bourbon'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'font-awesome-rails'

# Form
gem 'bootstrap_form'

# Use jquery as the JavaScript library
gem 'jquery-rails'
gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc

# support
gem 'meta-tags'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end

