default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: MINE.0ki8
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: yawainu_development

test:
  <<: *default
  database: yawainu_test

production:
  <<: *default
  database: yawainu_production
  username: yawainu
  password: <%= ENV['YAWAINU_DATABASE_PASSWORD'] %>
